// Code generated by github.com/jim-minter/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"sync"

	"github.com/ugorji/go/codec"

	pkg "github.com/Azure/ARO-RP/pkg/api"
)

type fakeMonitorDocumentTrigger func(context.Context, *pkg.MonitorDocument) error
type fakeMonitorDocumentQuery func(MonitorDocumentClient, *Query, *Options) MonitorDocumentRawIterator

var _ MonitorDocumentClient = &FakeMonitorDocumentClient{}

func NewFakeMonitorDocumentClient(h *codec.JsonHandle) *FakeMonitorDocumentClient {
	return &FakeMonitorDocumentClient{
		docs:              make(map[string][]byte),
		triggers:          make(map[string]fakeMonitorDocumentTrigger),
		queries:           make(map[string]fakeMonitorDocumentQuery),
		jsonHandle:        h,
		lock:              &sync.RWMutex{},
		sorter:            func(in []*pkg.MonitorDocument) {},
		checkDocsConflict: func(*pkg.MonitorDocument, *pkg.MonitorDocument) bool { return false },
	}
}

type FakeMonitorDocumentClient struct {
	docs       map[string][]byte
	jsonHandle *codec.JsonHandle
	lock       *sync.RWMutex
	triggers   map[string]fakeMonitorDocumentTrigger
	queries    map[string]fakeMonitorDocumentQuery
	sorter     func([]*pkg.MonitorDocument)

	// returns true if documents conflict
	checkDocsConflict func(*pkg.MonitorDocument, *pkg.MonitorDocument) bool

	// unavailable, if not nil, is an error to throw when attempting to
	// communicate with this Client
	unavailable error
}

func (c *FakeMonitorDocumentClient) decodeMonitorDocument(s []byte) (*pkg.MonitorDocument, error) {
	res := &pkg.MonitorDocument{}
	err := codec.NewDecoderBytes(s, c.jsonHandle).Decode(&res)
	return res, err
}

func (c *FakeMonitorDocumentClient) encodeMonitorDocument(doc *pkg.MonitorDocument) ([]byte, error) {
	res := make([]byte, 0)
	err := codec.NewEncoderBytes(&res, c.jsonHandle).Encode(doc)
	if err != nil {
		return nil, err
	}
	return res, err
}

func (c *FakeMonitorDocumentClient) MakeUnavailable(err error) {
	c.lock.Lock()
	defer c.lock.Unlock()
	c.unavailable = err
}

func (c *FakeMonitorDocumentClient) UseSorter(sorter func([]*pkg.MonitorDocument)) {
	c.sorter = sorter
}

func (c *FakeMonitorDocumentClient) UseDocumentConflictChecker(checker func(*pkg.MonitorDocument, *pkg.MonitorDocument) bool) {
	c.checkDocsConflict = checker
}

func (c *FakeMonitorDocumentClient) InjectTrigger(trigger string, impl fakeMonitorDocumentTrigger) {
	c.triggers[trigger] = impl
}

func (c *FakeMonitorDocumentClient) InjectQuery(query string, impl fakeMonitorDocumentQuery) {
	c.queries[query] = impl
}

func (c *FakeMonitorDocumentClient) encodeAndCopy(doc *pkg.MonitorDocument) (*pkg.MonitorDocument, []byte, error) {
	encoded, err := c.encodeMonitorDocument(doc)
	if err != nil {
		return nil, nil, err
	}
	res, err := c.decodeMonitorDocument(encoded)
	if err != nil {
		return nil, nil, err
	}
	return res, encoded, err
}

func (c *FakeMonitorDocumentClient) apply(ctx context.Context, partitionkey string, doc *pkg.MonitorDocument, options *Options, isNew bool) (*pkg.MonitorDocument, error) {
	var docExists bool
	c.lock.Lock()
	defer c.lock.Unlock()

	if options != nil {
		err := c.processPreTriggers(ctx, doc, options)
		if err != nil {
			return nil, err
		}
	}

	res, enc, err := c.encodeAndCopy(doc)
	if err != nil {
		return nil, err
	}

	for _, ext := range c.docs {
		dec, err := c.decodeMonitorDocument(ext)
		if err != nil {
			return nil, err
		}

		if dec.ID == res.ID {
			// If the document exists in the database, we want to error out in a
			// create but mark the document as extant so it can be replaced if
			// it is an update
			if isNew {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			} else {
				docExists = true
			}
		} else {
			if c.checkDocsConflict(dec, res) {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			}
		}
	}

	if !isNew && !docExists {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}

	c.docs[doc.ID] = enc
	return res, nil
}

func (c *FakeMonitorDocumentClient) Create(ctx context.Context, partitionkey string, doc *pkg.MonitorDocument, options *Options) (*pkg.MonitorDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	return c.apply(ctx, partitionkey, doc, options, true)
}

func (c *FakeMonitorDocumentClient) Replace(ctx context.Context, partitionkey string, doc *pkg.MonitorDocument, options *Options) (*pkg.MonitorDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	return c.apply(ctx, partitionkey, doc, options, false)
}

func (c *FakeMonitorDocumentClient) List(*Options) MonitorDocumentIterator {
	if c.unavailable != nil {
		return NewFakeMonitorDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	docs := make([]*pkg.MonitorDocument, 0, len(c.docs))
	for _, d := range c.docs {
		r, err := c.decodeMonitorDocument(d)
		if err != nil {
			return NewFakeMonitorDocumentClientErroringRawIterator(err)
		}
		docs = append(docs, r)
	}
	c.sorter(docs)
	return NewFakeMonitorDocumentClientRawIterator(docs, 0)
}

func (c *FakeMonitorDocumentClient) ListAll(ctx context.Context, opts *Options) (*pkg.MonitorDocuments, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	iter := c.List(opts)
	monitorDocuments, err := iter.Next(ctx, -1)
	if err != nil {
		return nil, err
	}
	return monitorDocuments, nil
}

func (c *FakeMonitorDocumentClient) Get(ctx context.Context, partitionkey string, documentId string, options *Options) (*pkg.MonitorDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	out, ext := c.docs[documentId]
	if !ext {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}
	return c.decodeMonitorDocument(out)
}

func (c *FakeMonitorDocumentClient) Delete(ctx context.Context, partitionKey string, doc *pkg.MonitorDocument, options *Options) error {
	if c.unavailable != nil {
		return c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	_, ext := c.docs[doc.ID]
	if !ext {
		return &Error{StatusCode: http.StatusNotFound}
	}

	delete(c.docs, doc.ID)
	return nil
}

func (c *FakeMonitorDocumentClient) ChangeFeed(*Options) MonitorDocumentIterator {
	if c.unavailable != nil {
		return NewFakeMonitorDocumentClientErroringRawIterator(c.unavailable)
	}
	return NewFakeMonitorDocumentClientErroringRawIterator(ErrNotImplemented)
}

func (c *FakeMonitorDocumentClient) processPreTriggers(ctx context.Context, doc *pkg.MonitorDocument, options *Options) error {
	for _, trigger := range options.PreTriggers {
		trig, ok := c.triggers[trigger]
		if ok {
			err := trig(ctx, doc)
			if err != nil {
				return err
			}
		} else {
			return ErrNotImplemented
		}
	}
	return nil
}

func (c *FakeMonitorDocumentClient) Query(name string, query *Query, options *Options) MonitorDocumentRawIterator {
	if c.unavailable != nil {
		return NewFakeMonitorDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	quer, ok := c.queries[query.Query]
	if ok {
		return quer(c, query, options)
	} else {
		return NewFakeMonitorDocumentClientErroringRawIterator(ErrNotImplemented)
	}
}

func (c *FakeMonitorDocumentClient) QueryAll(ctx context.Context, partitionkey string, query *Query, options *Options) (*pkg.MonitorDocuments, error) {
	iter := c.Query("", query, options)
	return iter.Next(ctx, -1)
}

// NewFakeMonitorDocumentClientRawIterator creates a RawIterator that will produce only
// MonitorDocuments from Next() and NextRaw().
func NewFakeMonitorDocumentClientRawIterator(docs []*pkg.MonitorDocument, continuation int) MonitorDocumentRawIterator {
	return &fakeMonitorDocumentClientRawIterator{docs: docs, continuation: continuation}
}

type fakeMonitorDocumentClientRawIterator struct {
	docs         []*pkg.MonitorDocument
	continuation int
	done         bool
}

func (i *fakeMonitorDocumentClientRawIterator) Next(ctx context.Context, maxItemCount int) (out *pkg.MonitorDocuments, err error) {
	err = i.NextRaw(ctx, maxItemCount, &out)
	return
}

func (i *fakeMonitorDocumentClientRawIterator) NextRaw(ctx context.Context, maxItemCount int, out interface{}) error {
	if i.done {
		return nil
	}

	var docs []*pkg.MonitorDocument
	if maxItemCount == -1 {
		docs = i.docs[i.continuation:]
		i.continuation = len(i.docs)
		i.done = true
	} else {
		max := i.continuation + maxItemCount
		if max > len(i.docs) {
			max = len(i.docs)
		}
		docs = i.docs[i.continuation:max]
		i.continuation += max
		i.done = i.Continuation() == ""
	}

	y := reflect.ValueOf(out)
	d := &pkg.MonitorDocuments{}
	d.MonitorDocuments = docs
	d.Count = len(d.MonitorDocuments)
	y.Elem().Set(reflect.ValueOf(d))
	return nil
}

func (i *fakeMonitorDocumentClientRawIterator) Continuation() string {
	if i.continuation >= len(i.docs) {
		return ""
	}
	return fmt.Sprintf("%d", i.continuation)
}

// fakeMonitorDocumentErroringRawIterator is a RawIterator that will return an error on use.
func NewFakeMonitorDocumentClientErroringRawIterator(err error) *fakeMonitorDocumentErroringRawIterator {
	return &fakeMonitorDocumentErroringRawIterator{err: err}
}

type fakeMonitorDocumentErroringRawIterator struct {
	err error
}

func (i *fakeMonitorDocumentErroringRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.MonitorDocuments, error) {
	return nil, i.err
}

func (i *fakeMonitorDocumentErroringRawIterator) NextRaw(context.Context, int, interface{}) error {
	return i.err
}

func (i *fakeMonitorDocumentErroringRawIterator) Continuation() string {
	return ""
}
