// Code generated by github.com/jim-minter/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"sync"

	"github.com/ugorji/go/codec"

	pkg "github.com/Azure/ARO-RP/pkg/api"
)

type fakeSubscriptionDocumentTrigger func(context.Context, *pkg.SubscriptionDocument) error
type fakeSubscriptionDocumentQuery func(SubscriptionDocumentClient, *Query, *Options) SubscriptionDocumentRawIterator

var _ SubscriptionDocumentClient = &FakeSubscriptionDocumentClient{}

func NewFakeSubscriptionDocumentClient(h *codec.JsonHandle) *FakeSubscriptionDocumentClient {
	return &FakeSubscriptionDocumentClient{
		docs:              make(map[string][]byte),
		triggers:          make(map[string]fakeSubscriptionDocumentTrigger),
		queries:           make(map[string]fakeSubscriptionDocumentQuery),
		jsonHandle:        h,
		lock:              &sync.RWMutex{},
		sorter:            func(in []*pkg.SubscriptionDocument) {},
		checkDocsConflict: func(*pkg.SubscriptionDocument, *pkg.SubscriptionDocument) bool { return false },
	}
}

type FakeSubscriptionDocumentClient struct {
	docs       map[string][]byte
	jsonHandle *codec.JsonHandle
	lock       *sync.RWMutex
	triggers   map[string]fakeSubscriptionDocumentTrigger
	queries    map[string]fakeSubscriptionDocumentQuery
	sorter     func([]*pkg.SubscriptionDocument)

	// returns true if documents conflict
	checkDocsConflict func(*pkg.SubscriptionDocument, *pkg.SubscriptionDocument) bool

	// unavailable, if not nil, is an error to throw when attempting to
	// communicate with this Client
	unavailable error
}

func (c *FakeSubscriptionDocumentClient) decodeSubscriptionDocument(s []byte) (*pkg.SubscriptionDocument, error) {
	res := &pkg.SubscriptionDocument{}
	err := codec.NewDecoderBytes(s, c.jsonHandle).Decode(&res)
	return res, err
}

func (c *FakeSubscriptionDocumentClient) encodeSubscriptionDocument(doc *pkg.SubscriptionDocument) ([]byte, error) {
	res := make([]byte, 0)
	err := codec.NewEncoderBytes(&res, c.jsonHandle).Encode(doc)
	if err != nil {
		return nil, err
	}
	return res, err
}

func (c *FakeSubscriptionDocumentClient) MakeUnavailable(err error) {
	c.lock.Lock()
	defer c.lock.Unlock()
	c.unavailable = err
}

func (c *FakeSubscriptionDocumentClient) UseSorter(sorter func([]*pkg.SubscriptionDocument)) {
	c.sorter = sorter
}

func (c *FakeSubscriptionDocumentClient) UseDocumentConflictChecker(checker func(*pkg.SubscriptionDocument, *pkg.SubscriptionDocument) bool) {
	c.checkDocsConflict = checker
}

func (c *FakeSubscriptionDocumentClient) InjectTrigger(trigger string, impl fakeSubscriptionDocumentTrigger) {
	c.triggers[trigger] = impl
}

func (c *FakeSubscriptionDocumentClient) InjectQuery(query string, impl fakeSubscriptionDocumentQuery) {
	c.queries[query] = impl
}

func (c *FakeSubscriptionDocumentClient) encodeAndCopy(doc *pkg.SubscriptionDocument) (*pkg.SubscriptionDocument, []byte, error) {
	encoded, err := c.encodeSubscriptionDocument(doc)
	if err != nil {
		return nil, nil, err
	}
	res, err := c.decodeSubscriptionDocument(encoded)
	if err != nil {
		return nil, nil, err
	}
	return res, encoded, err
}

func (c *FakeSubscriptionDocumentClient) apply(ctx context.Context, partitionkey string, doc *pkg.SubscriptionDocument, options *Options, isNew bool) (*pkg.SubscriptionDocument, error) {
	var docExists bool
	c.lock.Lock()
	defer c.lock.Unlock()

	if options != nil {
		err := c.processPreTriggers(ctx, doc, options)
		if err != nil {
			return nil, err
		}
	}

	res, enc, err := c.encodeAndCopy(doc)
	if err != nil {
		return nil, err
	}

	for _, ext := range c.docs {
		dec, err := c.decodeSubscriptionDocument(ext)
		if err != nil {
			return nil, err
		}

		if dec.ID == res.ID {
			// If the document exists in the database, we want to error out in a
			// create but mark the document as extant so it can be replaced if
			// it is an update
			if isNew {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			} else {
				docExists = true
			}
		} else {
			if c.checkDocsConflict(dec, res) {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			}
		}
	}

	if !isNew && !docExists {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}

	c.docs[doc.ID] = enc
	return res, nil
}

func (c *FakeSubscriptionDocumentClient) Create(ctx context.Context, partitionkey string, doc *pkg.SubscriptionDocument, options *Options) (*pkg.SubscriptionDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	return c.apply(ctx, partitionkey, doc, options, true)
}

func (c *FakeSubscriptionDocumentClient) Replace(ctx context.Context, partitionkey string, doc *pkg.SubscriptionDocument, options *Options) (*pkg.SubscriptionDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	return c.apply(ctx, partitionkey, doc, options, false)
}

func (c *FakeSubscriptionDocumentClient) List(*Options) SubscriptionDocumentIterator {
	if c.unavailable != nil {
		return NewFakeSubscriptionDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	docs := make([]*pkg.SubscriptionDocument, 0, len(c.docs))
	for _, d := range c.docs {
		r, err := c.decodeSubscriptionDocument(d)
		if err != nil {
			return NewFakeSubscriptionDocumentClientErroringRawIterator(err)
		}
		docs = append(docs, r)
	}
	c.sorter(docs)
	return NewFakeSubscriptionDocumentClientRawIterator(docs, 0)
}

func (c *FakeSubscriptionDocumentClient) ListAll(ctx context.Context, opts *Options) (*pkg.SubscriptionDocuments, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	iter := c.List(opts)
	subscriptionDocuments, err := iter.Next(ctx, -1)
	if err != nil {
		return nil, err
	}
	return subscriptionDocuments, nil
}

func (c *FakeSubscriptionDocumentClient) Get(ctx context.Context, partitionkey string, documentId string, options *Options) (*pkg.SubscriptionDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	out, ext := c.docs[documentId]
	if !ext {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}
	return c.decodeSubscriptionDocument(out)
}

func (c *FakeSubscriptionDocumentClient) Delete(ctx context.Context, partitionKey string, doc *pkg.SubscriptionDocument, options *Options) error {
	if c.unavailable != nil {
		return c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	_, ext := c.docs[doc.ID]
	if !ext {
		return &Error{StatusCode: http.StatusNotFound}
	}

	delete(c.docs, doc.ID)
	return nil
}

func (c *FakeSubscriptionDocumentClient) ChangeFeed(*Options) SubscriptionDocumentIterator {
	if c.unavailable != nil {
		return NewFakeSubscriptionDocumentClientErroringRawIterator(c.unavailable)
	}
	return NewFakeSubscriptionDocumentClientErroringRawIterator(ErrNotImplemented)
}

func (c *FakeSubscriptionDocumentClient) processPreTriggers(ctx context.Context, doc *pkg.SubscriptionDocument, options *Options) error {
	for _, trigger := range options.PreTriggers {
		trig, ok := c.triggers[trigger]
		if ok {
			err := trig(ctx, doc)
			if err != nil {
				return err
			}
		} else {
			return ErrNotImplemented
		}
	}
	return nil
}

func (c *FakeSubscriptionDocumentClient) Query(name string, query *Query, options *Options) SubscriptionDocumentRawIterator {
	if c.unavailable != nil {
		return NewFakeSubscriptionDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	quer, ok := c.queries[query.Query]
	if ok {
		return quer(c, query, options)
	} else {
		return NewFakeSubscriptionDocumentClientErroringRawIterator(ErrNotImplemented)
	}
}

func (c *FakeSubscriptionDocumentClient) QueryAll(ctx context.Context, partitionkey string, query *Query, options *Options) (*pkg.SubscriptionDocuments, error) {
	iter := c.Query("", query, options)
	return iter.Next(ctx, -1)
}

// NewFakeSubscriptionDocumentClientRawIterator creates a RawIterator that will produce only
// SubscriptionDocuments from Next() and NextRaw().
func NewFakeSubscriptionDocumentClientRawIterator(docs []*pkg.SubscriptionDocument, continuation int) SubscriptionDocumentRawIterator {
	return &fakeSubscriptionDocumentClientRawIterator{docs: docs, continuation: continuation}
}

type fakeSubscriptionDocumentClientRawIterator struct {
	docs         []*pkg.SubscriptionDocument
	continuation int
	done         bool
}

func (i *fakeSubscriptionDocumentClientRawIterator) Next(ctx context.Context, maxItemCount int) (out *pkg.SubscriptionDocuments, err error) {
	err = i.NextRaw(ctx, maxItemCount, &out)
	return
}

func (i *fakeSubscriptionDocumentClientRawIterator) NextRaw(ctx context.Context, maxItemCount int, out interface{}) error {
	if i.done {
		return nil
	}

	var docs []*pkg.SubscriptionDocument
	if maxItemCount == -1 {
		docs = i.docs[i.continuation:]
		i.continuation = len(i.docs)
		i.done = true
	} else {
		max := i.continuation + maxItemCount
		if max > len(i.docs) {
			max = len(i.docs)
		}
		docs = i.docs[i.continuation:max]
		i.continuation += max
		i.done = i.Continuation() == ""
	}

	y := reflect.ValueOf(out)
	d := &pkg.SubscriptionDocuments{}
	d.SubscriptionDocuments = docs
	d.Count = len(d.SubscriptionDocuments)
	y.Elem().Set(reflect.ValueOf(d))
	return nil
}

func (i *fakeSubscriptionDocumentClientRawIterator) Continuation() string {
	if i.continuation >= len(i.docs) {
		return ""
	}
	return fmt.Sprintf("%d", i.continuation)
}

// fakeSubscriptionDocumentErroringRawIterator is a RawIterator that will return an error on use.
func NewFakeSubscriptionDocumentClientErroringRawIterator(err error) *fakeSubscriptionDocumentErroringRawIterator {
	return &fakeSubscriptionDocumentErroringRawIterator{err: err}
}

type fakeSubscriptionDocumentErroringRawIterator struct {
	err error
}

func (i *fakeSubscriptionDocumentErroringRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.SubscriptionDocuments, error) {
	return nil, i.err
}

func (i *fakeSubscriptionDocumentErroringRawIterator) NextRaw(context.Context, int, interface{}) error {
	return i.err
}

func (i *fakeSubscriptionDocumentErroringRawIterator) Continuation() string {
	return ""
}
