// Code generated by github.com/jim-minter/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/http"
	"sync"

	"github.com/ugorji/go/codec"

	pkg "github.com/Azure/ARO-RP/pkg/api"
)

type FakeBillingDocumentTrigger func(context.Context, *pkg.BillingDocument) error
type FakeBillingDocumentQuery func(BillingDocumentClient, *Query, *Options) BillingDocumentRawIterator

var _ BillingDocumentClient = &FakeBillingDocumentClient{}

func NewFakeBillingDocumentClient(h *codec.JsonHandle, uniqueKeys []string) *FakeBillingDocumentClient {
	return &FakeBillingDocumentClient{
		docs:       make(map[string][]byte),
		triggers:   make(map[string]FakeBillingDocumentTrigger),
		queries:    make(map[string]FakeBillingDocumentQuery),
		uniqueKeys: uniqueKeys,
		jsonHandle: h,
		lock:       &sync.RWMutex{},
		sorter:     func(in []*pkg.BillingDocument) {},
	}
}

type FakeBillingDocumentClient struct {
	docs       map[string][]byte
	jsonHandle *codec.JsonHandle
	lock       *sync.RWMutex
	triggers   map[string]FakeBillingDocumentTrigger
	queries    map[string]FakeBillingDocumentQuery
	uniqueKeys []string
	sorter     func([]*pkg.BillingDocument)

	// unavailable, if not nil, is an error to throw when attempting to
	// communicate with this Client
	unavailable error
}

func decodeBillingDocument(s []byte, handle *codec.JsonHandle) (*pkg.BillingDocument, error) {
	res := &pkg.BillingDocument{}
	err := codec.NewDecoder(bytes.NewBuffer(s), handle).Decode(&res)
	return res, err
}

func decodeBillingDocumentToMap(s []byte, handle *codec.JsonHandle) (map[interface{}]interface{}, error) {
	var res interface{}
	err := codec.NewDecoder(bytes.NewBuffer(s), handle).Decode(&res)
	if err != nil {
		return nil, err
	}
	ret, ok := res.(map[interface{}]interface{})
	if !ok {
		return nil, errors.New("Could not coerce")
	}
	return ret, err
}

func encodeBillingDocument(doc *pkg.BillingDocument, handle *codec.JsonHandle) (res []byte, err error) {
	buf := &bytes.Buffer{}
	err = codec.NewEncoder(buf, handle).Encode(doc)
	if err != nil {
		return
	}
	res = buf.Bytes()
	return
}

func (c *FakeBillingDocumentClient) MakeUnavailable(err error) {
	c.unavailable = err
}

func (c *FakeBillingDocumentClient) UseSorter(sorter func([]*pkg.BillingDocument)) {
	c.sorter = sorter
}

func (c *FakeBillingDocumentClient) encodeAndCopy(doc *pkg.BillingDocument) (*pkg.BillingDocument, []byte, error) {
	encoded, err := encodeBillingDocument(doc, c.jsonHandle)
	if err != nil {
		return nil, nil, err
	}
	res, err := decodeBillingDocument(encoded, c.jsonHandle)
	if err != nil {
		return nil, nil, err
	}
	return res, encoded, err
}

func (c *FakeBillingDocumentClient) Create(ctx context.Context, partitionkey string, doc *pkg.BillingDocument, options *Options) (*pkg.BillingDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	if options != nil {
		err := c.processPreTriggers(ctx, doc, options)
		if err != nil {
			return nil, err
		}
	}

	res, enc, err := c.encodeAndCopy(doc)
	if err != nil {
		return nil, err
	}
	docAsMap, err := decodeBillingDocumentToMap(enc, c.jsonHandle)
	if err != nil {
		return nil, err
	}

	for _, ext := range c.docs {
		extDecoded, err := decodeBillingDocumentToMap(ext, c.jsonHandle)
		if err != nil {
			return nil, err
		}

		for _, key := range c.uniqueKeys {
			var ourKeyStr string
			var theirKeyStr string
			ourKey, ourKeyOk := docAsMap[key]
			if ourKeyOk {
				ourKeyStr, ourKeyOk = ourKey.(string)
			}
			theirKey, theirKeyOk := extDecoded[key]
			if theirKeyOk {
				theirKeyStr, theirKeyOk = theirKey.(string)
			}
			if ourKeyOk && theirKeyOk && ourKeyStr != "" && ourKeyStr == theirKeyStr {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			}
		}
	}

	c.docs[doc.ID] = enc
	return res, nil
}

func (c *FakeBillingDocumentClient) List(*Options) BillingDocumentIterator {
	if c.unavailable != nil {
		return NewFakeBillingDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	docs := make([]*pkg.BillingDocument, 0, len(c.docs))
	for _, d := range c.docs {
		r, err := decodeBillingDocument(d, c.jsonHandle)
		if err != nil {
			return NewFakeBillingDocumentClientErroringRawIterator(err)
		}
		docs = append(docs, r)
	}
	c.sorter(docs)
	return NewFakeBillingDocumentClientRawIterator(docs, 0)
}

func (c *FakeBillingDocumentClient) ListAll(context.Context, *Options) (*pkg.BillingDocuments, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	billingDocuments := &pkg.BillingDocuments{
		Count:            len(c.docs),
		BillingDocuments: make([]*pkg.BillingDocument, 0, len(c.docs)),
	}

	for _, d := range c.docs {
		dec, err := decodeBillingDocument(d, c.jsonHandle)
		if err != nil {
			return nil, err
		}
		billingDocuments.BillingDocuments = append(billingDocuments.BillingDocuments, dec)
	}
	c.sorter(billingDocuments.BillingDocuments)
	return billingDocuments, nil
}

func (c *FakeBillingDocumentClient) Get(ctx context.Context, partitionkey string, documentId string, options *Options) (*pkg.BillingDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	out, ext := c.docs[documentId]
	if !ext {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}
	return decodeBillingDocument(out, c.jsonHandle)
}

func (c *FakeBillingDocumentClient) Replace(ctx context.Context, partitionkey string, doc *pkg.BillingDocument, options *Options) (*pkg.BillingDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	_, exists := c.docs[doc.ID]
	if !exists {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}

	if options != nil {
		err := c.processPreTriggers(ctx, doc, options)
		if err != nil {
			return nil, err
		}
	}

	res, enc, err := c.encodeAndCopy(doc)
	if err != nil {
		return nil, err
	}
	c.docs[doc.ID] = enc
	return res, nil
}

func (c *FakeBillingDocumentClient) Delete(ctx context.Context, partitionKey string, doc *pkg.BillingDocument, options *Options) error {
	if c.unavailable != nil {
		return c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	_, ext := c.docs[doc.ID]
	if !ext {
		return &Error{StatusCode: http.StatusNotFound}
	}

	delete(c.docs, doc.ID)
	return nil
}

func (c *FakeBillingDocumentClient) ChangeFeed(*Options) BillingDocumentIterator {
	if c.unavailable != nil {
		return NewFakeBillingDocumentClientErroringRawIterator(c.unavailable)
	}
	return NewFakeBillingDocumentClientErroringRawIterator(ErrNotImplemented)
}

func (c *FakeBillingDocumentClient) processPreTriggers(ctx context.Context, doc *pkg.BillingDocument, options *Options) error {
	for _, trigger := range options.PreTriggers {
		trig, ok := c.triggers[trigger]
		if ok {
			err := trig(ctx, doc)
			if err != nil {
				return err
			}
		} else {
			return ErrNotImplemented
		}
	}
	return nil
}

func (c *FakeBillingDocumentClient) Query(name string, query *Query, options *Options) BillingDocumentRawIterator {
	if c.unavailable != nil {
		return NewFakeBillingDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	quer, ok := c.queries[query.Query]
	if ok {
		return quer(c, query, options)
	} else {
		return NewFakeBillingDocumentClientErroringRawIterator(ErrNotImplemented)
	}
}

func (c *FakeBillingDocumentClient) QueryAll(ctx context.Context, partitionkey string, query *Query, options *Options) (*pkg.BillingDocuments, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	quer, ok := c.queries[query.Query]
	if ok {
		items := quer(c, query, options)
		res := &pkg.BillingDocuments{}
		err := items.NextRaw(ctx, -1, res)
		return res, err
	} else {
		return nil, ErrNotImplemented
	}
}

func (c *FakeBillingDocumentClient) InjectTrigger(trigger string, impl FakeBillingDocumentTrigger) {
	c.triggers[trigger] = impl
}

func (c *FakeBillingDocumentClient) InjectQuery(query string, impl FakeBillingDocumentQuery) {
	c.queries[query] = impl
}

// NewFakeBillingDocumentClientRawIterator creates a RawIterator that will produce only
// BillingDocuments from Next() and NextRaw().
func NewFakeBillingDocumentClientRawIterator(docs []*pkg.BillingDocument, continuation int) BillingDocumentRawIterator {
	return &fakeBillingDocumentClientRawIterator{docs: docs, continuation: continuation}
}

type fakeBillingDocumentClientRawIterator struct {
	docs         []*pkg.BillingDocument
	continuation int
}

func (i *fakeBillingDocumentClientRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.BillingDocuments, error) {
	out := &pkg.BillingDocuments{}
	err := i.NextRaw(ctx, maxItemCount, out)

	if out.Count == 0 {
		return nil, nil
	}
	return out, err
}

func (i *fakeBillingDocumentClientRawIterator) NextRaw(ctx context.Context, maxItemCount int, out interface{}) error {
	if i.continuation >= len(i.docs) {
		return nil
	}

	var docs []*pkg.BillingDocument
	if maxItemCount == -1 {
		docs = i.docs[i.continuation:]
		i.continuation = len(i.docs)
	} else {
		max := i.continuation + maxItemCount
		if max > len(i.docs) {
			max = len(i.docs)
		}
		docs = i.docs[i.continuation:max]
		i.continuation += max
	}

	d := out.(*pkg.BillingDocuments)
	d.BillingDocuments = docs
	d.Count = len(d.BillingDocuments)
	return nil
}

func (i *fakeBillingDocumentClientRawIterator) Continuation() string {
	if i.continuation >= len(i.docs) {
		return ""
	}
	return fmt.Sprintf("%d", i.continuation)
}

// fakeBillingDocumentErroringRawIterator is a RawIterator that will return an error on use.
func NewFakeBillingDocumentClientErroringRawIterator(err error) *fakeBillingDocumentErroringRawIterator {
	return &fakeBillingDocumentErroringRawIterator{err: err}
}

type fakeBillingDocumentErroringRawIterator struct {
	err error
}

func (i *fakeBillingDocumentErroringRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.BillingDocuments, error) {
	return nil, i.err
}

func (i *fakeBillingDocumentErroringRawIterator) NextRaw(context.Context, int, interface{}) error {
	return i.err
}

func (i *fakeBillingDocumentErroringRawIterator) Continuation() string {
	return ""
}
