// Code generated by github.com/jim-minter/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"sync"

	"github.com/ugorji/go/codec"

	pkg "github.com/Azure/ARO-RP/pkg/api"
)

type fakeOpenShiftClusterDocumentTrigger func(context.Context, *pkg.OpenShiftClusterDocument) error
type fakeOpenShiftClusterDocumentQuery func(OpenShiftClusterDocumentClient, *Query, *Options) OpenShiftClusterDocumentRawIterator

var _ OpenShiftClusterDocumentClient = &FakeOpenShiftClusterDocumentClient{}

func NewFakeOpenShiftClusterDocumentClient(h *codec.JsonHandle) *FakeOpenShiftClusterDocumentClient {
	return &FakeOpenShiftClusterDocumentClient{
		docs:              make(map[string][]byte),
		triggers:          make(map[string]fakeOpenShiftClusterDocumentTrigger),
		queries:           make(map[string]fakeOpenShiftClusterDocumentQuery),
		jsonHandle:        h,
		lock:              &sync.RWMutex{},
		sorter:            func(in []*pkg.OpenShiftClusterDocument) {},
		checkDocsConflict: func(*pkg.OpenShiftClusterDocument, *pkg.OpenShiftClusterDocument) bool { return false },
	}
}

type FakeOpenShiftClusterDocumentClient struct {
	docs       map[string][]byte
	jsonHandle *codec.JsonHandle
	lock       *sync.RWMutex
	triggers   map[string]fakeOpenShiftClusterDocumentTrigger
	queries    map[string]fakeOpenShiftClusterDocumentQuery
	sorter     func([]*pkg.OpenShiftClusterDocument)

	// returns true if documents conflict
	checkDocsConflict func(*pkg.OpenShiftClusterDocument, *pkg.OpenShiftClusterDocument) bool

	// unavailable, if not nil, is an error to throw when attempting to
	// communicate with this Client
	unavailable error
}

func (c *FakeOpenShiftClusterDocumentClient) decodeOpenShiftClusterDocument(s []byte) (*pkg.OpenShiftClusterDocument, error) {
	res := &pkg.OpenShiftClusterDocument{}
	err := codec.NewDecoderBytes(s, c.jsonHandle).Decode(&res)
	return res, err
}

func (c *FakeOpenShiftClusterDocumentClient) encodeOpenShiftClusterDocument(doc *pkg.OpenShiftClusterDocument) ([]byte, error) {
	res := make([]byte, 0)
	err := codec.NewEncoderBytes(&res, c.jsonHandle).Encode(doc)
	if err != nil {
		return nil, err
	}
	return res, err
}

func (c *FakeOpenShiftClusterDocumentClient) MakeUnavailable(err error) {
	c.lock.Lock()
	defer c.lock.Unlock()
	c.unavailable = err
}

func (c *FakeOpenShiftClusterDocumentClient) UseSorter(sorter func([]*pkg.OpenShiftClusterDocument)) {
	c.sorter = sorter
}

func (c *FakeOpenShiftClusterDocumentClient) UseDocumentConflictChecker(checker func(*pkg.OpenShiftClusterDocument, *pkg.OpenShiftClusterDocument) bool) {
	c.checkDocsConflict = checker
}

func (c *FakeOpenShiftClusterDocumentClient) InjectTrigger(trigger string, impl fakeOpenShiftClusterDocumentTrigger) {
	c.triggers[trigger] = impl
}

func (c *FakeOpenShiftClusterDocumentClient) InjectQuery(query string, impl fakeOpenShiftClusterDocumentQuery) {
	c.queries[query] = impl
}

func (c *FakeOpenShiftClusterDocumentClient) encodeAndCopy(doc *pkg.OpenShiftClusterDocument) (*pkg.OpenShiftClusterDocument, []byte, error) {
	encoded, err := c.encodeOpenShiftClusterDocument(doc)
	if err != nil {
		return nil, nil, err
	}
	res, err := c.decodeOpenShiftClusterDocument(encoded)
	if err != nil {
		return nil, nil, err
	}
	return res, encoded, err
}

func (c *FakeOpenShiftClusterDocumentClient) apply(ctx context.Context, partitionkey string, doc *pkg.OpenShiftClusterDocument, options *Options, isNew bool) (*pkg.OpenShiftClusterDocument, error) {
	var docExists bool
	c.lock.Lock()
	defer c.lock.Unlock()

	if options != nil {
		err := c.processPreTriggers(ctx, doc, options)
		if err != nil {
			return nil, err
		}
	}

	res, enc, err := c.encodeAndCopy(doc)
	if err != nil {
		return nil, err
	}

	for _, ext := range c.docs {
		dec, err := c.decodeOpenShiftClusterDocument(ext)
		if err != nil {
			return nil, err
		}

		if dec.ID == res.ID {
			// If the document exists in the database, we want to error out in a
			// create but mark the document as extant so it can be replaced if
			// it is an update
			if isNew {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			} else {
				docExists = true
			}
		} else {
			if c.checkDocsConflict(dec, res) {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			}
		}
	}

	if !isNew && !docExists {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}

	c.docs[doc.ID] = enc
	return res, nil
}

func (c *FakeOpenShiftClusterDocumentClient) Create(ctx context.Context, partitionkey string, doc *pkg.OpenShiftClusterDocument, options *Options) (*pkg.OpenShiftClusterDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	return c.apply(ctx, partitionkey, doc, options, true)
}

func (c *FakeOpenShiftClusterDocumentClient) Replace(ctx context.Context, partitionkey string, doc *pkg.OpenShiftClusterDocument, options *Options) (*pkg.OpenShiftClusterDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	return c.apply(ctx, partitionkey, doc, options, false)
}

func (c *FakeOpenShiftClusterDocumentClient) List(*Options) OpenShiftClusterDocumentIterator {
	if c.unavailable != nil {
		return NewFakeOpenShiftClusterDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	docs := make([]*pkg.OpenShiftClusterDocument, 0, len(c.docs))
	for _, d := range c.docs {
		r, err := c.decodeOpenShiftClusterDocument(d)
		if err != nil {
			return NewFakeOpenShiftClusterDocumentClientErroringRawIterator(err)
		}
		docs = append(docs, r)
	}
	c.sorter(docs)
	return NewFakeOpenShiftClusterDocumentClientRawIterator(docs, 0)
}

func (c *FakeOpenShiftClusterDocumentClient) ListAll(ctx context.Context, opts *Options) (*pkg.OpenShiftClusterDocuments, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	iter := c.List(opts)
	openShiftClusterDocuments, err := iter.Next(ctx, -1)
	if err != nil {
		return nil, err
	}
	return openShiftClusterDocuments, nil
}

func (c *FakeOpenShiftClusterDocumentClient) Get(ctx context.Context, partitionkey string, documentId string, options *Options) (*pkg.OpenShiftClusterDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	out, ext := c.docs[documentId]
	if !ext {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}
	return c.decodeOpenShiftClusterDocument(out)
}

func (c *FakeOpenShiftClusterDocumentClient) Delete(ctx context.Context, partitionKey string, doc *pkg.OpenShiftClusterDocument, options *Options) error {
	if c.unavailable != nil {
		return c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	_, ext := c.docs[doc.ID]
	if !ext {
		return &Error{StatusCode: http.StatusNotFound}
	}

	delete(c.docs, doc.ID)
	return nil
}

func (c *FakeOpenShiftClusterDocumentClient) ChangeFeed(*Options) OpenShiftClusterDocumentIterator {
	if c.unavailable != nil {
		return NewFakeOpenShiftClusterDocumentClientErroringRawIterator(c.unavailable)
	}
	return NewFakeOpenShiftClusterDocumentClientErroringRawIterator(ErrNotImplemented)
}

func (c *FakeOpenShiftClusterDocumentClient) processPreTriggers(ctx context.Context, doc *pkg.OpenShiftClusterDocument, options *Options) error {
	for _, trigger := range options.PreTriggers {
		trig, ok := c.triggers[trigger]
		if ok {
			err := trig(ctx, doc)
			if err != nil {
				return err
			}
		} else {
			return ErrNotImplemented
		}
	}
	return nil
}

func (c *FakeOpenShiftClusterDocumentClient) Query(name string, query *Query, options *Options) OpenShiftClusterDocumentRawIterator {
	if c.unavailable != nil {
		return NewFakeOpenShiftClusterDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	quer, ok := c.queries[query.Query]
	if ok {
		return quer(c, query, options)
	} else {
		return NewFakeOpenShiftClusterDocumentClientErroringRawIterator(ErrNotImplemented)
	}
}

func (c *FakeOpenShiftClusterDocumentClient) QueryAll(ctx context.Context, partitionkey string, query *Query, options *Options) (*pkg.OpenShiftClusterDocuments, error) {
	iter := c.Query("", query, options)
	return iter.Next(ctx, -1)
}

// NewFakeOpenShiftClusterDocumentClientRawIterator creates a RawIterator that will produce only
// OpenShiftClusterDocuments from Next() and NextRaw().
func NewFakeOpenShiftClusterDocumentClientRawIterator(docs []*pkg.OpenShiftClusterDocument, continuation int) OpenShiftClusterDocumentRawIterator {
	return &fakeOpenShiftClusterDocumentClientRawIterator{docs: docs, continuation: continuation}
}

type fakeOpenShiftClusterDocumentClientRawIterator struct {
	docs         []*pkg.OpenShiftClusterDocument
	continuation int
	done         bool
}

func (i *fakeOpenShiftClusterDocumentClientRawIterator) Next(ctx context.Context, maxItemCount int) (out *pkg.OpenShiftClusterDocuments, err error) {
	err = i.NextRaw(ctx, maxItemCount, &out)
	return
}

func (i *fakeOpenShiftClusterDocumentClientRawIterator) NextRaw(ctx context.Context, maxItemCount int, out interface{}) error {
	if i.done {
		return nil
	}

	var docs []*pkg.OpenShiftClusterDocument
	if maxItemCount == -1 {
		docs = i.docs[i.continuation:]
		i.continuation = len(i.docs)
		i.done = true
	} else {
		max := i.continuation + maxItemCount
		if max > len(i.docs) {
			max = len(i.docs)
		}
		docs = i.docs[i.continuation:max]
		i.continuation += max
		i.done = i.Continuation() == ""
	}

	y := reflect.ValueOf(out)
	d := &pkg.OpenShiftClusterDocuments{}
	d.OpenShiftClusterDocuments = docs
	d.Count = len(d.OpenShiftClusterDocuments)
	y.Elem().Set(reflect.ValueOf(d))
	return nil
}

func (i *fakeOpenShiftClusterDocumentClientRawIterator) Continuation() string {
	if i.continuation >= len(i.docs) {
		return ""
	}
	return fmt.Sprintf("%d", i.continuation)
}

// fakeOpenShiftClusterDocumentErroringRawIterator is a RawIterator that will return an error on use.
func NewFakeOpenShiftClusterDocumentClientErroringRawIterator(err error) *fakeOpenShiftClusterDocumentErroringRawIterator {
	return &fakeOpenShiftClusterDocumentErroringRawIterator{err: err}
}

type fakeOpenShiftClusterDocumentErroringRawIterator struct {
	err error
}

func (i *fakeOpenShiftClusterDocumentErroringRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.OpenShiftClusterDocuments, error) {
	return nil, i.err
}

func (i *fakeOpenShiftClusterDocumentErroringRawIterator) NextRaw(context.Context, int, interface{}) error {
	return i.err
}

func (i *fakeOpenShiftClusterDocumentErroringRawIterator) Continuation() string {
	return ""
}
