// Code generated by github.com/jim-minter/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/http"
	"sync"

	"github.com/ugorji/go/codec"

	pkg "github.com/Azure/ARO-RP/pkg/api"
)

type FakeAsyncOperationDocumentTrigger func(context.Context, *pkg.AsyncOperationDocument) error
type FakeAsyncOperationDocumentQuery func(AsyncOperationDocumentClient, *Query, *Options) AsyncOperationDocumentRawIterator

var _ AsyncOperationDocumentClient = &FakeAsyncOperationDocumentClient{}

func NewFakeAsyncOperationDocumentClient(h *codec.JsonHandle, uniqueKeys []string) *FakeAsyncOperationDocumentClient {
	return &FakeAsyncOperationDocumentClient{
		docs:       make(map[string][]byte),
		triggers:   make(map[string]FakeAsyncOperationDocumentTrigger),
		queries:    make(map[string]FakeAsyncOperationDocumentQuery),
		uniqueKeys: uniqueKeys,
		jsonHandle: h,
		lock:       &sync.RWMutex{},
		sorter:     func(in []*pkg.AsyncOperationDocument) {},
	}
}

type FakeAsyncOperationDocumentClient struct {
	docs       map[string][]byte
	jsonHandle *codec.JsonHandle
	lock       *sync.RWMutex
	triggers   map[string]FakeAsyncOperationDocumentTrigger
	queries    map[string]FakeAsyncOperationDocumentQuery
	uniqueKeys []string
	sorter     func([]*pkg.AsyncOperationDocument)

	// unavailable, if not nil, is an error to throw when attempting to
	// communicate with this Client
	unavailable error
}

func decodeAsyncOperationDocument(s []byte, handle *codec.JsonHandle) (*pkg.AsyncOperationDocument, error) {
	res := &pkg.AsyncOperationDocument{}
	err := codec.NewDecoder(bytes.NewBuffer(s), handle).Decode(&res)
	return res, err
}

func decodeAsyncOperationDocumentToMap(s []byte, handle *codec.JsonHandle) (map[interface{}]interface{}, error) {
	var res interface{}
	err := codec.NewDecoder(bytes.NewBuffer(s), handle).Decode(&res)
	if err != nil {
		return nil, err
	}
	ret, ok := res.(map[interface{}]interface{})
	if !ok {
		return nil, errors.New("Could not coerce")
	}
	return ret, err
}

func encodeAsyncOperationDocument(doc *pkg.AsyncOperationDocument, handle *codec.JsonHandle) (res []byte, err error) {
	buf := &bytes.Buffer{}
	err = codec.NewEncoder(buf, handle).Encode(doc)
	if err != nil {
		return
	}
	res = buf.Bytes()
	return
}

func (c *FakeAsyncOperationDocumentClient) MakeUnavailable(err error) {
	c.unavailable = err
}

func (c *FakeAsyncOperationDocumentClient) UseSorter(sorter func([]*pkg.AsyncOperationDocument)) {
	c.sorter = sorter
}

func (c *FakeAsyncOperationDocumentClient) encodeAndCopy(doc *pkg.AsyncOperationDocument) (*pkg.AsyncOperationDocument, []byte, error) {
	encoded, err := encodeAsyncOperationDocument(doc, c.jsonHandle)
	if err != nil {
		return nil, nil, err
	}
	res, err := decodeAsyncOperationDocument(encoded, c.jsonHandle)
	if err != nil {
		return nil, nil, err
	}
	return res, encoded, err
}

func (c *FakeAsyncOperationDocumentClient) Create(ctx context.Context, partitionkey string, doc *pkg.AsyncOperationDocument, options *Options) (*pkg.AsyncOperationDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	if options != nil {
		err := c.processPreTriggers(ctx, doc, options)
		if err != nil {
			return nil, err
		}
	}

	res, enc, err := c.encodeAndCopy(doc)
	if err != nil {
		return nil, err
	}
	docAsMap, err := decodeAsyncOperationDocumentToMap(enc, c.jsonHandle)
	if err != nil {
		return nil, err
	}

	for _, ext := range c.docs {
		extDecoded, err := decodeAsyncOperationDocumentToMap(ext, c.jsonHandle)
		if err != nil {
			return nil, err
		}

		for _, key := range c.uniqueKeys {
			var ourKeyStr string
			var theirKeyStr string
			ourKey, ourKeyOk := docAsMap[key]
			if ourKeyOk {
				ourKeyStr, ourKeyOk = ourKey.(string)
			}
			theirKey, theirKeyOk := extDecoded[key]
			if theirKeyOk {
				theirKeyStr, theirKeyOk = theirKey.(string)
			}
			if ourKeyOk && theirKeyOk && ourKeyStr != "" && ourKeyStr == theirKeyStr {
				return nil, &Error{
					StatusCode: http.StatusPreconditionFailed,
					Message:    "Entity with the specified id already exists in the system",
				}
			}
		}
	}

	c.docs[doc.ID] = enc
	return res, nil
}

func (c *FakeAsyncOperationDocumentClient) List(*Options) AsyncOperationDocumentIterator {
	if c.unavailable != nil {
		return NewFakeAsyncOperationDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	docs := make([]*pkg.AsyncOperationDocument, 0, len(c.docs))
	for _, d := range c.docs {
		r, err := decodeAsyncOperationDocument(d, c.jsonHandle)
		if err != nil {
			return NewFakeAsyncOperationDocumentClientErroringRawIterator(err)
		}
		docs = append(docs, r)
	}
	c.sorter(docs)
	return NewFakeAsyncOperationDocumentClientRawIterator(docs, 0)
}

func (c *FakeAsyncOperationDocumentClient) ListAll(context.Context, *Options) (*pkg.AsyncOperationDocuments, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	asyncOperationDocuments := &pkg.AsyncOperationDocuments{
		Count:                   len(c.docs),
		AsyncOperationDocuments: make([]*pkg.AsyncOperationDocument, 0, len(c.docs)),
	}

	for _, d := range c.docs {
		dec, err := decodeAsyncOperationDocument(d, c.jsonHandle)
		if err != nil {
			return nil, err
		}
		asyncOperationDocuments.AsyncOperationDocuments = append(asyncOperationDocuments.AsyncOperationDocuments, dec)
	}
	return asyncOperationDocuments, nil
}

func (c *FakeAsyncOperationDocumentClient) Get(ctx context.Context, partitionkey string, documentId string, options *Options) (*pkg.AsyncOperationDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	out, ext := c.docs[documentId]
	if !ext {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}
	return decodeAsyncOperationDocument(out, c.jsonHandle)
}

func (c *FakeAsyncOperationDocumentClient) Replace(ctx context.Context, partitionkey string, doc *pkg.AsyncOperationDocument, options *Options) (*pkg.AsyncOperationDocument, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	_, exists := c.docs[doc.ID]
	if !exists {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}

	if options != nil {
		err := c.processPreTriggers(ctx, doc, options)
		if err != nil {
			return nil, err
		}
	}

	res, enc, err := c.encodeAndCopy(doc)
	if err != nil {
		return nil, err
	}
	c.docs[doc.ID] = enc
	return res, nil
}

func (c *FakeAsyncOperationDocumentClient) Delete(ctx context.Context, partitionKey string, doc *pkg.AsyncOperationDocument, options *Options) error {
	if c.unavailable != nil {
		return c.unavailable
	}
	c.lock.Lock()
	defer c.lock.Unlock()

	_, ext := c.docs[doc.ID]
	if !ext {
		return &Error{StatusCode: http.StatusNotFound}
	}

	delete(c.docs, doc.ID)
	return nil
}

func (c *FakeAsyncOperationDocumentClient) ChangeFeed(*Options) AsyncOperationDocumentIterator {
	if c.unavailable != nil {
		return NewFakeAsyncOperationDocumentClientErroringRawIterator(c.unavailable)
	}
	return NewFakeAsyncOperationDocumentClientErroringRawIterator(ErrNotImplemented)
}

func (c *FakeAsyncOperationDocumentClient) processPreTriggers(ctx context.Context, doc *pkg.AsyncOperationDocument, options *Options) error {
	for _, trigger := range options.PreTriggers {
		trig, ok := c.triggers[trigger]
		if ok {
			err := trig(ctx, doc)
			if err != nil {
				return err
			}
		} else {
			return ErrNotImplemented
		}
	}
	return nil
}

func (c *FakeAsyncOperationDocumentClient) Query(name string, query *Query, options *Options) AsyncOperationDocumentRawIterator {
	if c.unavailable != nil {
		return NewFakeAsyncOperationDocumentClientErroringRawIterator(c.unavailable)
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	quer, ok := c.queries[query.Query]
	if ok {
		return quer(c, query, options)
	} else {
		return NewFakeAsyncOperationDocumentClientErroringRawIterator(ErrNotImplemented)
	}
}

func (c *FakeAsyncOperationDocumentClient) QueryAll(ctx context.Context, partitionkey string, query *Query, options *Options) (*pkg.AsyncOperationDocuments, error) {
	if c.unavailable != nil {
		return nil, c.unavailable
	}
	c.lock.RLock()
	defer c.lock.RUnlock()

	quer, ok := c.queries[query.Query]
	if ok {
		items := quer(c, query, options)
		res := &pkg.AsyncOperationDocuments{}
		err := items.NextRaw(ctx, -1, res)
		return res, err
	} else {
		return nil, ErrNotImplemented
	}
}

func (c *FakeAsyncOperationDocumentClient) InjectTrigger(trigger string, impl FakeAsyncOperationDocumentTrigger) {
	c.triggers[trigger] = impl
}

func (c *FakeAsyncOperationDocumentClient) InjectQuery(query string, impl FakeAsyncOperationDocumentQuery) {
	c.queries[query] = impl
}

// NewFakeAsyncOperationDocumentClientRawIterator creates a RawIterator that will produce only
// AsyncOperationDocuments from Next() and NextRaw().
func NewFakeAsyncOperationDocumentClientRawIterator(docs []*pkg.AsyncOperationDocument, continuation int) AsyncOperationDocumentRawIterator {
	return &fakeAsyncOperationDocumentClientRawIterator{docs: docs, continuation: continuation}
}

type fakeAsyncOperationDocumentClientRawIterator struct {
	docs         []*pkg.AsyncOperationDocument
	continuation int
}

func (i *fakeAsyncOperationDocumentClientRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.AsyncOperationDocuments, error) {
	out := &pkg.AsyncOperationDocuments{}
	err := i.NextRaw(ctx, maxItemCount, out)

	if out.Count == 0 {
		return nil, nil
	}
	return out, err
}

func (i *fakeAsyncOperationDocumentClientRawIterator) NextRaw(ctx context.Context, maxItemCount int, out interface{}) error {
	if i.continuation >= len(i.docs) {
		return nil
	}

	var docs []*pkg.AsyncOperationDocument
	if maxItemCount == -1 {
		docs = i.docs[i.continuation:]
		i.continuation = len(i.docs)
	} else {
		max := i.continuation + maxItemCount
		if max > len(i.docs) {
			max = len(i.docs)
		}
		docs = i.docs[i.continuation:max]
		i.continuation += max
	}

	d := out.(*pkg.AsyncOperationDocuments)
	d.AsyncOperationDocuments = docs
	d.Count = len(d.AsyncOperationDocuments)
	return nil
}

func (i *fakeAsyncOperationDocumentClientRawIterator) Continuation() string {
	if i.continuation >= len(i.docs) {
		return ""
	}
	return fmt.Sprintf("%d", i.continuation)
}

// fakeAsyncOperationDocumentErroringRawIterator is a RawIterator that will return an error on use.
func NewFakeAsyncOperationDocumentClientErroringRawIterator(err error) *fakeAsyncOperationDocumentErroringRawIterator {
	return &fakeAsyncOperationDocumentErroringRawIterator{err: err}
}

type fakeAsyncOperationDocumentErroringRawIterator struct {
	err error
}

func (i *fakeAsyncOperationDocumentErroringRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.AsyncOperationDocuments, error) {
	return nil, i.err
}

func (i *fakeAsyncOperationDocumentErroringRawIterator) NextRaw(context.Context, int, interface{}) error {
	return i.err
}

func (i *fakeAsyncOperationDocumentErroringRawIterator) Continuation() string {
	return ""
}
